### ISSUE TITLE
opusenc/windows: flac Error parsing input file:

### ISSUE THREAD

**Issue by grummisch** [xiph/opus-tools#21]
mp3tag has been used to remove all tags from the flac file.
opusenc -V: opusenc opus-tools 0.1.10-9-gbd65450 (using libopus 1.2)
from https://archive.mozilla.org/pub/opus/win64/opus-tools-0.1.10-win64.zip, 
accessed from https://opus-codec.org/downloads/
(I have to rely on binaries, can't build myself)

**Comment by vlakoff** [comment]
Official binaries for Windows don't support FLAC input (at least for the time being).

I also commented about it here: https://github.com/xiph/opus-tools/issues/15#issuecomment-414014890

**Comment by vlakoff** [comment]
Meanwhile, you can encode using [FFmpeg](https://ffmpeg.org/).

See: https://superuser.com/questions/516806/how-to-encode-audio-with-opus-codec
