### ISSUE TITLE
Audio artifacts when encoded using opusenc.

### ISSUE THREAD

**Issue by arun54321** [xiph/opus-tools#35]
I hear artifacts when audio is encoded by opusenc but not through libopus(ffmpeg). I used same bitrate and complexity on both tools.

http://goo.gl/zzF4z7

when encoded using opusenc there is sudden skips on 01:41 and 3:59.

**Comment by theonlycure** [comment]
Having same problem with opusenc and latest ffmpeg 4.0.2 does same thing. Not every encode but many. Skips and some other artifacts. Using libopus 1.3-rc. Ubuntu Server 18.04.1

**Comment by moisesmcardona** [comment]
Which rc version are you using? You can verify using `opusenc.exe -V`.  

For example, it should output something like this:
```
opusenc opus-tools 0.1.10-80-g1a646c4-dirty (using libopus 1.3-rc-22-g4a643d98-dirty)
Copyright (C) 2008-2018 Xiph.Org Foundation
```

That first line tells the version used.

I've been compiling the source code whenever a commit is done and I don't head any artifacts with the latest commits done.

**Comment by theonlycure** [comment]
opusenc opus-tools 0.1.10 (using libopus 1.3-rc)

**Comment by arun54321** [comment]
Not all encodes have artifacts. I have used latest version in arch linux repos.

`opusenc -V
opusenc opus-tools 0.1.10 (using libopus 1.2.1)
Copyright (C) 2008-2017 Xiph.Org Foundation
`

**Comment by theonlycure** [comment]
OK rebuilt from git.
opusenc opus-tools 0.1.10 (using libopus 1.3-rc-22-g4a643d98)
Back to do some encodes

**Comment by theonlycure** [comment]
Seems to have fixes my issues. Off topic but the encodes seem to sound better, old and new ones alike. Great Job.

**Comment by mark4o** [comment]
It appears that this issue was resolved when rebuilding with the latest version, so I will go ahead and close this.  Please re-open if you feel there is still an issue in opusenc.  Thanks!
