### ISSUE TITLE
.lib files for windows

### ISSUE THREAD

**Issue by lars1298** [xiph/opus-tools#43]
Is there any place where the .lib files required to build the windows tools can be downloaded?  I get errors for all of these: 

opus.lib
libogg_static.lib
opusfile.lib
opusenc.lib

 built opus and libogg_static, to which 'libFLAC_static.lib' started throwing errors.

Is it expected to manually build all of these projects to build opus-tools for windows?

**Comment by mark4o** [comment]
If you don't want to build it yourself, a Windows binary can be downloaded from: https://www.opus-codec.org/downloads/

**Comment by lars1298** [comment]
I would like to make changes to the opusenc.exe tool, but I ran into a lot of issue trying to build all the other tools.  Lots of include directories missing and I'm not sure where the lib files need to be.  Is it required to build all 5 tools/libraries just to edit opusenc?  Is it possible to post a version of the libs somewhere, or is there a document which explains the required directory structure to build these out of the box?
