### ISSUE TITLE
Use Smart HTTP protocol on git.xiph.org site

### ISSUE THREAD

**Issue by Chocobo1** [xiph/opus-tools#5]
This is actually an issue of the `https://git.xiph.org/` site and applies to all repos hosted.
https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols#The-HTTP-Protocols

Fail clone from git.xiph.org:

``` bat
> git clone https://git.xiph.org/opus-tools.git --depth 1
Cloning into 'opus-tools'...
fatal: dumb http transport does not support --depth
```

Successful clone from github:

``` bat
> git clone https://github.com/xiph/opus-tools.git --depth 1
Cloning into 'opus-tools'...
remote: Counting objects: 71, done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 71 (delta 11), reused 47 (delta 8), pack-reused 0
Unpacking objects: 100% (71/71), done.
Checking connectivity... done.
```

**Comment by Chocobo1** [comment]
A quote from the ProGit book:
>Generally you would either choose to run a read/write Smart HTTP server or simply have the files accessible as read-only in the Dumb manner. It’s rare to run a mix of the two services.

If this behavior is intended, sorry for the noise. (well, too bad the `depth` option isn't avaliable)

**Comment by ePirat** [comment]
The project migrated officially to our Gitlab instance now, it seems to work fine:

```
git clone https://gitlab.xiph.org/xiph/opus-tools.git --depth 1
```

so I will close this issue, feel free to re-open if it still does not work for you.

**Comment by Chocobo1** [comment]
What about the future of https://git.xiph.org ? Is it going to be redirected to https://gitlab.xiph.org in the near future?

**Comment by ePirat** [comment]
To not break stuff, Gitlab will be mirrored back to git.xiph.org opus-tools for some time, as there is no way to redirect SSH Git in an easy way. Once all projects migrated to Gitlab, at some point git.xiph.org will probably just redirect for https to the new locations.
