### ISSUE TITLE
FEC not enabled

### ISSUE THREAD

**Issue by boborjan2** [xiph/opus-tools#57]
Hi, 

opusenc does not enable fec even if expect-loss is not zero.  Only the expected loss is passed to libopus, inband_fec is not set.
We used the following revisions.
libopusenc-0.2.1
opus-1.3.1
opusfile-0.12
opus-tools-0.2

Regards,
Viktor

**Comment by mark4o** [comment]
The expected packet loss is used for more than just to calculate the FEC bitrate when FEC is enabled.  A higher expected packet loss will also reduce inter-frame dependencies.  FEC must be enabled separately if desired.
