### ISSUE TITLE
audio gets cut short by almost 3 seconds when encoding from FLAC

### ISSUE THREAD

**Issue by damian101** [xiph/opus-tools#71]
Reencoding the FLAC file does not help, it happens with all FLAC files. Encoding from WAV works fine.
I'm on Arch Linux, using opus-tools-git from the AUR (https://aur.archlinux.org/packages/opus-tools-git).

**Comment by Zapeth** [comment]
It looks like this is caused by the latest commit, I wrote a comment about it (https://github.com/xiph/opus-tools/issues/61#issuecomment-1119772254), but no reply yet

**Comment by tdaede** [comment]
Cut short, or cut from the beginning?

I can't seem to reproduce here. Could you tell me what the first 4 bytes of the FLAC file are?

**Comment by tdaede** [comment]
Nevermind, I found a file that reproduces.
