### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ShalokShalom** [xiph/opus-tools#8]
There is no stable release since 3 years.

**Comment by bugmenot2** [comment]
[Opus-tools 0.1.10 was tagged 17 days ago](https://github.com/xiph/opus-tools/releases/tag/v0.1.10), but for whatever reason it wasn't officially released... If you're looking for Windows binaries [here's my personal, 100% unofficial Win64 build :smile:](https://myfile.org/Y1Y5tebebe/opus-tools-0.1.10-opus-1.2-alpha2-win64.7z)

**Comment by ShalokShalom** [comment]
No, Linux 

Thanks anyway :+1:

**Comment by rillian** [comment]
A source package for 0.1.10 is available now from https://ftp.osuosl.org/pub/xiph/releases/opus/opus-tools-0.1.10.tar.gz

Linux binaries are available in Debian testing (and Ubuntu 17.04) but it looks like Fedora hasn't updated.

Anyway, thanks for the suggestion. We did manage to make a release. :)
